[package]
name = "sodomight"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
mge-audio = { path = "../../crates/mge-audio" }
mge-content = { path = "../../crates/mge-content" }
mge-core = { path = "../../crates/mge-core" }
mge-net = { path = "../../crates/mge-net" }
mge-render = { path = "../../crates/mge-render" }
mge-replication = { path = "../../crates/mge-replication" }
mge-save = { path = "../../crates/mge-save" }
mge-server-core = { path = "../../crates/mge-server-core" }
pollster.workspace = true
winit.workspace = true

[lints]
workspace = true
