[workspace]
resolver = "2"
members = [
    "crates/miyukini-kernel",
    "crates/demo-logging-lifecycle",
    "crates/miyukini-spm-cms-content",
    "crates/miyukini-spm-cms-hierarchy",
    "crates/miyukini-spm-cms-taxonomies",
    "crates/miyukini-spm-cms-media",
    "crates/miyukini-spm-cms-publication",
    "crates/miyukini-spm-cms-search",
    "crates/mini-cms",
    "crates/kindmother",
    "crates/miyukini-strongfather"
]
