[package]
name = "everbuddy"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
keywords.workspace = true
categories.workspace = true
description = "EverBuddy - Gestionnaire de compatibilité et migration du Miyukini Core System"

[dependencies]
miyukini-kernel = { path = "../miyukini-kernel" }
kindmother = { path = "../kindmother" }

[dev-dependencies]

[lints.rust]
unsafe_code = "forbid"
missing_docs = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
doc_markdown = "allow"
