# @id: MGE-Platform @do: kernel @role: back-end @layer: 1 @human: miyuk
# mge-platform — MGE platform: window, GPU init, input mapping

[package]
name = "mge-platform"
version.workspace = true
edition.workspace = true
description = "MGE platform: window, GPU init, input mapping"

[dependencies]
mge-math = { path = "../mge-math" }
serde = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
pollster = "0.4"

[dev-dependencies]
# Aucune (tests platform necessitent GPU)

[lints]
workspace = true
