blank_issues_enabled: true
contact_links:
  - name: Miyukini Cloud Documentation
    url: https://github.com/StudioMiyukini/miyucloud/wiki
    about: Please check the documentation before opening an issue