// @id: MGE-AnimPack-Mirror @do: mirror-generation @role: back-end @layer: 6 @human: francois
//! Horizontal mirror generation for 4-direction to 8-direction sprites.
//!
//! In isometric games, characters are typically rendered in 4 directions
//! (S, SW, W, NW) and the other 4 (N, NE, E, SE) are generated by
//! horizontal mirroring:
//!
//! - SE = mirror(SW)
//! - E  = mirror(W)
//! - NE = mirror(NW)
//! - N  = S (or mirror(S), identical for symmetric sprites)

use crate::errors::AnimPackError;

/// A frame with its name, pixel data, and dimensions.
pub type NamedFrame = (String, Vec<u8>, u32, u32);

/// Mirror an RGBA image horizontally (left-right flip).
///
/// Returns a new pixel buffer with the same dimensions.
pub fn mirror_horizontal(pixels: &[u8], width: u32, height: u32) -> Result<Vec<u8>, AnimPackError> {
    let expected = (width * height * 4) as usize;
    if pixels.len() != expected {
        return Err(AnimPackError::InvalidPixelData {
            name: "mirror_input".to_string(),
            expected,
            got: pixels.len(),
        });
    }

    let mut out = vec![0u8; pixels.len()];
    for y in 0..height {
        for x in 0..width {
            let src = ((y * width + x) * 4) as usize;
            let dst_x = width - 1 - x;
            let dst = ((y * width + dst_x) * 4) as usize;
            out[dst..dst + 4].copy_from_slice(&pixels[src..src + 4]);
        }
    }
    Ok(out)
}

/// Direction mapping for mirror generation.
///
/// Given 4 rendered directions (S, SW, W, NW), generates the
/// 4 mirrored directions (SE, E, NE, N).
const MIRROR_MAP: &[(&str, &str)] = &[
    ("sw", "se"), // SE = mirror(SW)
    ("w", "e"),   // E  = mirror(W)
    ("nw", "ne"), // NE = mirror(NW)
];

/// Generate mirrored frames from the 4 rendered directions.
///
/// Takes frames named with directions S, SW, W, NW and generates
/// SE (from SW), E (from W), NE (from NW). The N direction is not
/// mirrored — it can be the same as S or provided separately.
///
/// Returns only the newly generated mirror frames.
pub fn generate_mirrors(frames: &[NamedFrame]) -> Result<Vec<NamedFrame>, AnimPackError> {
    let mut mirrors = Vec::new();

    for &(src_dir, dst_dir) in MIRROR_MAP {
        // Find all frames matching the source direction.
        let source_frames: Vec<&NamedFrame> = frames
            .iter()
            .filter(|(name, _, _, _)| {
                // Check if the direction component matches.
                // Frame names follow: entity_action_DIR_frame.png
                extract_direction(name) == Some(src_dir)
            })
            .collect();

        for (name, pixels, width, height) in &source_frames {
            let mirrored_pixels = mirror_horizontal(pixels, *width, *height)?;
            let mirrored_name = replace_direction(name, dst_dir);
            mirrors.push((mirrored_name, mirrored_pixels, *width, *height));
        }
    }

    Ok(mirrors)
}

/// Extract the direction component from a frame name.
///
/// Assumes the naming convention: `{entity}_{action}_{dir}_{frame}.png`
/// where direction is the second-to-last underscore-separated component.
fn extract_direction(name: &str) -> Option<&str> {
    let stem = name.strip_suffix(".png").unwrap_or(name);
    let parts: Vec<&str> = stem.split('_').collect();
    if parts.len() >= 4 {
        Some(parts[parts.len() - 2])
    } else {
        None
    }
}

/// Replace the direction component in a frame name.
fn replace_direction(name: &str, new_dir: &str) -> String {
    let stem = name.strip_suffix(".png").unwrap_or(name);
    let mut parts: Vec<&str> = stem.split('_').collect();
    if parts.len() >= 4 {
        let idx = parts.len() - 2;
        parts[idx] = new_dir;
    }
    format!("{}.png", parts.join("_"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mirror_horizontal_2x2() {
        // 2x2 image: [Red, Green] / [Blue, Yellow]
        let pixels: Vec<u8> = vec![
            255, 0, 0, 255, // (0,0) red
            0, 255, 0, 255, // (1,0) green
            0, 0, 255, 255, // (0,1) blue
            255, 255, 0, 255, // (1,1) yellow
        ];
        let mirrored = mirror_horizontal(&pixels, 2, 2).unwrap();
        assert_eq!(
            mirrored,
            vec![
                0, 255, 0, 255, // (0,0) green (was at x=1)
                255, 0, 0, 255, // (1,0) red (was at x=0)
                255, 255, 0, 255, // (0,1) yellow (was at x=1)
                0, 0, 255, 255, // (1,1) blue (was at x=0)
            ]
        );
    }

    #[test]
    fn mirror_horizontal_preserves_size() {
        let w = 4;
        let h = 3;
        let pixels = vec![128u8; (w * h * 4) as usize];
        let mirrored = mirror_horizontal(&pixels, w, h).unwrap();
        assert_eq!(mirrored.len(), pixels.len());
    }

    #[test]
    fn mirror_horizontal_invalid_data() {
        let result = mirror_horizontal(&[0, 1, 2], 2, 2);
        assert!(result.is_err());
    }

    #[test]
    fn mirror_horizontal_double_is_identity() {
        let pixels: Vec<u8> = vec![
            255, 0, 0, 255, 0, 255, 0, 255, 0, 0, 255, 255, 255, 255, 0, 255,
        ];
        let once = mirror_horizontal(&pixels, 2, 2).unwrap();
        let twice = mirror_horizontal(&once, 2, 2).unwrap();
        assert_eq!(twice, pixels);
    }

    #[test]
    fn generate_mirrors_from_four_directions() {
        let pixel_1x1 = vec![255u8, 0, 0, 255]; // 1x1 red pixel

        let frames: Vec<NamedFrame> = vec![
            (
                "fallen_idle_sw_000.png".to_string(),
                pixel_1x1.clone(),
                1,
                1,
            ),
            (
                "fallen_idle_w_000.png".to_string(),
                pixel_1x1.clone(),
                1,
                1,
            ),
            (
                "fallen_idle_nw_000.png".to_string(),
                pixel_1x1.clone(),
                1,
                1,
            ),
        ];

        let mirrors = generate_mirrors(&frames).unwrap();

        // Should generate 3 mirror frames: se, e, ne
        assert_eq!(mirrors.len(), 3, "Expected 3 mirror frames, got {}", mirrors.len());

        let names: Vec<&str> = mirrors.iter().map(|(n, _, _, _)| n.as_str()).collect();
        assert!(names.contains(&"fallen_idle_se_000.png"));
        assert!(names.contains(&"fallen_idle_e_000.png"));
        assert!(names.contains(&"fallen_idle_ne_000.png"));
    }

    #[test]
    fn generate_mirrors_empty_input() {
        let mirrors = generate_mirrors(&[]).unwrap();
        assert!(mirrors.is_empty());
    }

    #[test]
    fn extract_direction_valid() {
        assert_eq!(extract_direction("fallen_idle_sw_000.png"), Some("sw"));
        assert_eq!(extract_direction("dark_elder_attack_ne_005.png"), Some("ne"));
    }

    #[test]
    fn extract_direction_invalid() {
        assert_eq!(extract_direction("bad.png"), None);
    }

    #[test]
    fn replace_direction_works() {
        let result = replace_direction("fallen_idle_sw_000.png", "se");
        assert_eq!(result, "fallen_idle_se_000.png");
    }
}
