@echo off
echo [MIP] Mise a jour de l'index sequences...
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0scripts\rebuild-sequences-index.ps1"
echo [MIP] Ouverture du portail...
start "" "%~dp0index.html"
