// @id: sd-impl-atlas @do: implement @role: back-end @layer: 2 @human: miyuk

//! Texture atlas descriptor and registry (CPU-side, no GPU types).
//!
//! Atlas descriptors are generated by `mge-packer` as TOML files.
//! This module handles parsing and frame lookup without requiring
//! a GPU device.

use std::collections::HashMap;

use serde::{Deserialize, Serialize};

use crate::errors::RenderError;

// ---------------------------------------------------------------------------
// AtlasFrame
// ---------------------------------------------------------------------------

/// A single rectangular frame inside a texture atlas.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AtlasFrame {
    /// Sprite name (e.g. `"grass_01"`, `"skeleton_walk_s_0"`).
    pub name: String,
    /// Pixel X offset inside the atlas PNG.
    pub x: u32,
    /// Pixel Y offset inside the atlas PNG.
    pub y: u32,
    /// Width of the frame in pixels.
    pub w: u32,
    /// Height of the frame in pixels.
    pub h: u32,
    /// Trim offset X (used by `mge-packer` when trimming transparent pixels).
    #[serde(default)]
    pub offset_x: f32,
    /// Trim offset Y.
    #[serde(default)]
    pub offset_y: f32,
    /// Whether the frame was trimmed.
    #[serde(default)]
    pub trimmed: bool,
    /// Original source image width before trimming.
    #[serde(default)]
    pub source_w: u32,
    /// Original source image height before trimming.
    #[serde(default)]
    pub source_h: u32,
}

// ---------------------------------------------------------------------------
// AtlasEntry (lightweight UV-centred alternative requested in spec)
// ---------------------------------------------------------------------------

/// Lightweight atlas entry carrying normalised UV coordinates.
///
/// This mirrors the `AtlasEntry` described in the task specification.
/// It is built from an [`AtlasFrame`] when the atlas pixel dimensions
/// are known.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AtlasEntry {
    /// Sprite identifier.
    pub id: String,
    /// Normalised U coordinate (left).
    pub u: f32,
    /// Normalised V coordinate (top).
    pub v: f32,
    /// Normalised width.
    pub w: f32,
    /// Normalised height.
    pub h: f32,
    /// Total number of animation frames (1 if static).
    pub frame_count: u32,
    /// Duration per animation frame in milliseconds.
    pub frame_duration_ms: u32,
}

// ---------------------------------------------------------------------------
// AtlasDescriptor (TOML root)
// ---------------------------------------------------------------------------

/// Root structure of a TOML atlas descriptor file generated by `mge-packer`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AtlasDescriptor {
    /// Ordered list of frames in the atlas.
    pub frames: Vec<AtlasFrame>,
}

// ---------------------------------------------------------------------------
// TextureAtlas (CPU-only)
// ---------------------------------------------------------------------------

/// CPU-side texture atlas: maps frame names to pixel rects.
///
/// GPU texture/bind-group creation is handled separately by the
/// [`Renderer`](crate::renderer::Renderer) when a device is available.
#[derive(Debug, Clone)]
pub struct TextureAtlas {
    /// Unique atlas identifier.
    pub id: String,
    /// Width of the atlas image in pixels.
    pub width: u32,
    /// Height of the atlas image in pixels.
    pub height: u32,
    /// Name-indexed frames.
    pub frames: HashMap<String, AtlasFrame>,
}

impl TextureAtlas {
    /// Build a `TextureAtlas` from a TOML descriptor string.
    ///
    /// The atlas dimensions are required to compute normalised UVs later.
    pub fn from_toml(
        atlas_id: &str,
        toml_content: &str,
        atlas_width: u32,
        atlas_height: u32,
    ) -> Result<Self, RenderError> {
        let descriptor: AtlasDescriptor =
            toml::from_str(toml_content).map_err(|e| RenderError::TomlParse {
                message: e.to_string(),
            })?;

        let frames: HashMap<String, AtlasFrame> = descriptor
            .frames
            .into_iter()
            .map(|f| (f.name.clone(), f))
            .collect();

        Ok(Self {
            id: atlas_id.to_string(),
            width: atlas_width,
            height: atlas_height,
            frames,
        })
    }

    /// Return normalised UV coordinates `[u_min, v_min, u_max, v_max]` for a
    /// named frame, or `None` if the frame does not exist.
    pub fn get_uv(&self, frame_name: &str) -> Option<[f32; 4]> {
        self.frames.get(frame_name).map(|f| {
            [
                f.x as f32 / self.width as f32,
                f.y as f32 / self.height as f32,
                (f.x + f.w) as f32 / self.width as f32,
                (f.y + f.h) as f32 / self.height as f32,
            ]
        })
    }

    /// Return the pixel dimensions `(w, h)` of a named frame.
    pub fn get_frame_size(&self, frame_name: &str) -> Option<(u32, u32)> {
        self.frames.get(frame_name).map(|f| (f.w, f.h))
    }
}

// ---------------------------------------------------------------------------
// AtlasRegistry
// ---------------------------------------------------------------------------

/// Registry of loaded texture atlases.
///
/// Provides O(1) lookup by atlas identifier.
#[derive(Debug, Clone, Default)]
pub struct AtlasRegistry {
    atlases: HashMap<String, TextureAtlas>,
}

impl AtlasRegistry {
    /// Create an empty registry.
    pub fn new() -> Self {
        Self::default()
    }

    /// Insert (or replace) an atlas.
    pub fn insert(&mut self, atlas: TextureAtlas) {
        self.atlases.insert(atlas.id.clone(), atlas);
    }

    /// Look up an atlas by identifier.
    pub fn get(&self, atlas_id: &str) -> Option<&TextureAtlas> {
        self.atlases.get(atlas_id)
    }

    /// Return the number of registered atlases.
    pub fn len(&self) -> usize {
        self.atlases.len()
    }

    /// Return `true` when the registry contains no atlases.
    pub fn is_empty(&self) -> bool {
        self.atlases.is_empty()
    }
}
