---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "miyucloud.fullname" . }}-config
data:
  MIYUCLOUD_SERVER_PORT: {{ .Values.config.server.port | quote }}
  MIYUCLOUD_SERVER_HOST: {{ .Values.config.server.host | quote }}
  {{- if .Values.config.server.baseUrl }}
  MIYUCLOUD_BASE_URL: {{ .Values.config.server.baseUrl | quote }}
  {{- end }}
  MIYUCLOUD_ENABLE_AUTH: {{ .Values.config.features.enableAuth | quote }}
  MIYUCLOUD_ENABLE_FILE_SHARING: {{ .Values.config.features.enableSharing | quote }}
  MIMALLOC_PURGE_DELAY: {{ .Values.config.mimalloc.purgeDelay | quote }}
  MIMALLOC_ALLOW_LARGE_OS_PAGES: {{ .Values.config.mimalloc.allowLargeOsPages | quote }}

  {{- if .Values.wopi.enabled }}
  MIYUCLOUD_WOPI_ENABLED: "true"
  MIYUCLOUD_WOPI_DISCOVERY_URL: "{{ .Values.config.server.baseUrl }}/hosting/discovery"
  {{- else }}
  MIYUCLOUD_WOPI_ENABLED: "false"
  {{- end }}