---
{{- if .Values.wopi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "miyucloud.fullname" . }}-wopi
  labels:
    {{- include "miyucloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: wopi
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.wopi.collabora.service.port }}
      targetPort: wopi
      protocol: TCP
      name: wopi
  selector:
    {{- include "miyucloud.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: wopi
{{- end }}